#!/usr/bin/env ruby
#
# Copyright 2017 Geoff Williams for Declarative Systems PTY LTD
# Copyright 2016 Geoff Williams for Puppet Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Inline bundler makes us always use bundler to bundle our bundles because
# there is a conflict for faraday version between puppet_forge and one of
# the other gems in use.  Bundler will automatically resolve this as long
# as its used at _any_ level.  This is equivalent to making a tempdir with
# a Gemfile and running from there, eg this restores functionality with the
# native ruby running outside of bundler (by forcing bundler to load)
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'arfor'
end


require 'escort'
require 'arfor'
require 'arfor/agent_installers'
require 'arfor/gems'
require 'arfor/platform_installer'
require 'pe_info/tarball'
require 'arfor/control_repo'
# require 'arfor/github_module'

# display help if nothing specified
ARGV.push('-h') if ARGV.empty?

Escort::App.create do |app|
  app.version Arfor::VERSION
  app.summary "Arfor"
  app.description "Handy bits and pieces for puppet"

  app.command :agent_installers do |command|
    command.summary "Download agents"
    command.description "Download agent installers locally for faster deployments"
    command.options do |opts|
      opts.opt(:print_urls,
        'Just print the URLS we would use, dont download anything',
        :long     => '--print-urls',
        :type     => :boolean,
      )
      opts.opt(:pe_tarball,
        'Point Arfor at a PE Master tarball to automatically obtain the correct installers',
        :long     => '--pe-tarball',
        :type     => :string,
      )
    end
    command.action do |options, arguments|
      cmd         = :agent_installers # FIXME obtain this automatically
      print_urls  = options[:global][:commands][cmd][:options][:print_urls]
      pe_tarball  = options[:global][:commands][cmd][:options][:pe_tarball]
      if pe_tarball
        pe_version, agent_version, supported_platforms = PeInfo::Tarball::inspect(pe_tarball)
      end
      Arfor::AgentInstallers::download(pe_version, agent_version, supported_platforms, print_urls)
    end

    app.command :gems do |command|
      command.summary "Download gems"
      command.description "Download required gems locally for faster deployments"
      command.action do |options, arguments|
        Arfor::Gems::download()
      end
    end

    app.command :platform_installer do |command|
      command.summary "Download PE Platform installer"
      command.description "Download Puppet Enterprise"
      command.options do |opts|
        opts.opt(:pe_version,
          'PE version to download, eg `2016.4.2`',
          :long    => '--pe-version',
          :type    => :string,
          :default => nil
        )
        opts.opt(:dist,
          'OS distribution to download, eg `el`',
          :long    => '--dist',
          :type    => :string,
          :default => nil
        )
        opts.opt(:rel,
          'OS distribution version to download, eg `7`',
          :long    => '--rel',
          :type    => :string,
          :default => nil
        )
        opts.opt(:arch,
          'OS distribution architecture to download, eg `x86_64`',
          :long    => '--arch',
          :default => nil
        )
      end
      command.action do |options, arguments|
        pe_version  = options[:global][:commands][:platform_installer][:options][:pe_version]
        dist        = options[:global][:commands][:platform_installer][:options][:dist]
        rel         = options[:global][:commands][:platform_installer][:options][:rel]
        arch        = options[:global][:commands][:platform_installer][:options][:arch]

        Arfor::PlatformInstaller::download(pe_version, dist, rel, arch)
      end
    end

    app.command :control_repo do |command|
      command.summary "Control Repository"
      command.description "Create a Puppet Control Repository, setup for testing with onceover"
      command.action do |options, arguments|
        Arfor::ControlRepo::create()
      end
    end

    app.command :github_module do |command|
      command.summary "Github Module"
      command.description "Create a new Puppet module enabled with PDQTest and upload to GitHub"
      command.action do |options, arguments|
        puts Arfor::GithubModule::create()
      end
    end

  end
end
